### ISSUE TITLE
Getting exception "com.github.javaparser.ParseProblemException"

### ISSUE THREAD

**Issue by nikitamehrotra12** [victorjmarin/sourcedg#1]
Hii,

I am trying to generate Program Dependence Graph using sourcedg. When I tried executing the file Test.java I got the exception "Exception in thread "main" com.github.javaparser.ParseProblemException: (line 1,col 10) Parse error. Found "int", expected one of  ";" "@" "class" "enum" "interface" "module" "open""
Below is the code for which I am trying to generate the PDG
`public static int srch()
  {
    int c, first, last, middle, n, search, array[];
    first  = 0;
    last   = n - 1;
    middle = (first + last)/2;

    while( first <= last )
    {
      if ( array[middle] < search )
        first = middle + 1;
      else if ( array[middle] == search )
      {
        return middle+1;
      }
      else
         last = middle - 1;

      middle = (first + last)/2;
   }
   if ( first > last )
     return 0;
  }
 `

And the stack trace is:

> Exception in thread "main" com.github.javaparser.ParseProblemException: (line 1,col 10) Parse error. Found "int", expected one of  ";" "@" "class" "enum" "interface" "module" "open"
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:10271)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:10130)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:179)
  com.github.javaparser.JavaParser.parse(JavaParser.java:126)
  com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:325)
  com.github.javaparser.JavaParser.parse(JavaParser.java:159)
  com.github.javaparser.JavaParser.parse(JavaParser.java:172)
  edu.rit.goal.sourcedg.builder.PDGBuilder.build(PDGBuilder.java:48)
  edu.rit.goal.sourcedg.Test.main(Test.java:19)

	at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:329)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:159)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:172)
	at edu.rit.goal.sourcedg.builder.PDGBuilder.build(PDGBuilder.java:48)
	at edu.rit.goal.sourcedg.Test.main(Test.java:19)

Process finished with exit code 1

**Comment by fgnm** [comment]
Since javaparser works as like Java, you cannot parse a single function, but you have to wrap it in a class
